Основы JS. Примитивные типы данных
js-tasks-ru/js-20230407_mihail64 pull request #2
Opened 2023-04-14 18:18 UTC by m4ex

2023-04-14 18:19 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-04-17 21:52 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let sortedArr = [...arr];
почему `let`?

2023-04-17 21:53 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    sortedArr.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2023-04-17 21:53 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  return Object.fromEntries(
good 👍

2023-04-17 21:53 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
>  export const omit = (obj, ...fields) => {
good 👍

2023-04-17 21:53 UTC, dosandk requested changes
решение sortStrings следует поправить

2023-04-18 17:37 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-04-18 17:39 UTC, m4ex commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let sortedArr = [...arr];
убрал в новой версии

2023-04-18 17:40 UTC, m4ex commented on 02-javascript-data-types/1-sort-strings/index.js
> +    sortedArr.reverse();
сделал

2023-04-18 17:43 UTC, m4ex commented
решение sortStrings переделал, но немного по своему, да там есть небольшое повторение кода, но лично на мой взгляд такой вариант читается лучше чем вариант с трюком с умножением на -1 о котором вы говорили на занятии

2023-04-20 22:12 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    "asc": (a, b) => a.localeCompare(b, ["ru", "en"], { sensitivity: "case", caseFirst: "upper" }),
строка 9 дублирует строку 10

2023-04-20 22:13 UTC, dosandk approved these changes
👍 good

2023-04-20 22:13 UTC, merged

2023-05-02 18:42 UTC, m4ex commented on 02-javascript-data-types/1-sort-strings/index.js
> +    "asc": (a, b) => a.localeCompare(b, ["ru", "en"], { sensitivity: "case", caseFirst: "upper" }),
на мой взгляд так код лучше читается, хотя может это с непривычки